# Generated by Django 4.0.4 on 2022-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_options_alter_discount_options_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاکتور ها', 'verbose_name_plural': 'فاکتور ها'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت ها', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='options',
        ),
        migrations.AddField(
            model_name='cart',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='product.option'),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='options',
        ),
        migrations.AddField(
            model_name='invoice',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='product.option'),
        ),
    ]
