# Generated by Django 4.0.4 on 2022-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'کد ورود',
                'verbose_name_plural': 'کد ورود',
            },
        ),
    ]
