# Generated by Django 3.1.14 on 2022-05-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'color'), (2, 'lenght'), (3, 'size')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'available'), (2, 'unavailable')], default=1),
        ),
    ]
