# Generated by Django 3.1.14 on 2022-05-24 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220524_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='value',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
