# Generated by Django 3.1.14 on 2022-05-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220524_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
    ]
