# Generated by Django 4.0.4 on 2022-06-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220529_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(null=True, to='product.option'),
        ),
    ]
