# Generated by Django 4.0.4 on 2022-06-27 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی سطح ۱', 'verbose_name_plural': 'دسته بندی سطح ۱'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیفات', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'ویژگی های انتخابی', 'verbose_name_plural': 'ویژگی های انتخابی'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'تصاویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'ويزگی ها', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'دسته بندی سطح ۲', 'verbose_name_plural': 'دسته بندی سطح ۲'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name': 'دسته بندی سطح ۳', 'verbose_name_plural': 'دسته بندی سطح ۳'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='نشانک'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'رنگ'), (2, 'طول'), (3, 'اندازه')], default=1, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.CharField(max_length=600, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, verbose_name='درباره محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=1, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.subsubcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام لاتین'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='product.option', verbose_name='ویژگی های انتخابی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(to='product.picture', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(to='product.property', verbose_name='ویژگی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'موجود'), (2, 'ناموجود')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=200, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی سطح ۱'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='نشانک'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='نشانک'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory', verbose_name='دسته بندی سطح ۲'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
